-- ════════════════════════════════════════════════════════════════════
-- RecruitAI — idempotent schema script
--
-- Safe to run on a FRESH or an ALREADY-POPULATED database. It only
-- creates what is missing:
--   * tables / columns / indexes use IF NOT EXISTS
--   * RLS is enabled (a no-op when already enabled)
--   * each policy is DROP IF EXISTS + CREATE, so re-running never errors
--
-- This consolidates supabase/migrations/* into one runnable file because
-- the original migrations are not idempotent (CREATE POLICY has no
-- IF NOT EXISTS). Paste this into the Supabase dashboard → SQL Editor.
-- ════════════════════════════════════════════════════════════════════

-- ── Tables ──────────────────────────────────────────────────────────

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  role text,
  experience text,
  hard_skills text,
  soft_skills text,
  certifications text,
  created_at timestamptz default now()
);
alter table public.jobs add column if not exists user_id uuid references auth.users(id) on delete cascade;

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  name text not null,
  profile_url text,
  profile_text text not null,
  skills text,
  experience text,
  match_score int default 0,
  match_reasoning text,
  created_at timestamptz default now()
);

create table if not exists public.interview_reports (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  notes text not null,
  strengths text,
  weaknesses text,
  recommendation text,
  created_at timestamptz default now()
);

create table if not exists public.knowledge_guides (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  concepts jsonb default '[]'::jsonb,
  interview_questions jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.boolean_searches (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  created_at timestamptz default now()
);

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text default 'recruiter' check (role in ('recruiter', 'candidate')),
  full_name text default '',
  created_at timestamptz default now()
);

create table if not exists public.candidate_notes (
  id bigserial primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  notes text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (candidate_id, user_id)
);

create table if not exists public.candidate_submissions (
  id bigserial primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_name text default '',
  status text default 'sourced' check (status in ('sourced', 'screened', 'submitted', 'interview', 'offered', 'joined', 'rejected')),
  submitted_at timestamptz,
  notes text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (candidate_id, job_id, user_id)
);

create table if not exists public.market_intelligence (
  id bigserial primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  data jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  unique (job_id, user_id)
);

-- ── Indexes ─────────────────────────────────────────────────────────

create index if not exists idx_candidates_job_id on public.candidates(job_id);
create index if not exists idx_candidates_match_score on public.candidates(match_score desc);
create index if not exists idx_interview_reports_candidate_id on public.interview_reports(candidate_id);
create index if not exists idx_jobs_user_id on public.jobs(user_id);
create index if not exists idx_knowledge_guides_job on public.knowledge_guides(job_id, user_id);
create index if not exists idx_boolean_searches_job on public.boolean_searches(job_id, user_id);
create index if not exists idx_submissions_job on public.candidate_submissions(job_id, user_id);
create index if not exists idx_submissions_candidate on public.candidate_submissions(candidate_id);
create index if not exists idx_market_intel_job on public.market_intelligence(job_id, user_id);

-- ── Row Level Security (no-op if already enabled) ───────────────────

alter table public.jobs                  enable row level security;
alter table public.candidates            enable row level security;
alter table public.interview_reports     enable row level security;
alter table public.knowledge_guides      enable row level security;
alter table public.boolean_searches      enable row level security;
alter table public.user_profiles         enable row level security;
alter table public.candidate_notes       enable row level security;
alter table public.candidate_submissions enable row level security;
alter table public.market_intelligence   enable row level security;

-- ── Policies (drop + create = safe to re-run) ───────────────────────

-- jobs: a user fully owns their own jobs
drop policy if exists "Users can view own jobs"   on public.jobs;
drop policy if exists "Users can insert own jobs" on public.jobs;
drop policy if exists "Users can update own jobs" on public.jobs;
drop policy if exists "Users can delete own jobs" on public.jobs;
create policy "Users can view own jobs"   on public.jobs for select using (auth.uid() = user_id);
create policy "Users can insert own jobs" on public.jobs for insert with check (auth.uid() = user_id);
create policy "Users can update own jobs" on public.jobs for update using (auth.uid() = user_id);
create policy "Users can delete own jobs" on public.jobs for delete using (auth.uid() = user_id);

-- candidates: accessible when the parent job belongs to the user
drop policy if exists "Users can view own candidates"   on public.candidates;
drop policy if exists "Users can insert own candidates" on public.candidates;
drop policy if exists "Users can update own candidates" on public.candidates;
drop policy if exists "Users can delete own candidates" on public.candidates;
create policy "Users can view own candidates" on public.candidates for select using (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);
create policy "Users can insert own candidates" on public.candidates for insert with check (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);
create policy "Users can update own candidates" on public.candidates for update using (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);
create policy "Users can delete own candidates" on public.candidates for delete using (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);

-- interview_reports: accessible when the parent job belongs to the user
drop policy if exists "Users can view own reports"   on public.interview_reports;
drop policy if exists "Users can insert own reports" on public.interview_reports;
create policy "Users can view own reports" on public.interview_reports for select using (
  exists (select 1 from public.jobs where jobs.id = interview_reports.job_id and jobs.user_id = auth.uid())
);
create policy "Users can insert own reports" on public.interview_reports for insert with check (
  exists (select 1 from public.jobs where jobs.id = interview_reports.job_id and jobs.user_id = auth.uid())
);

-- knowledge_guides: a user fully owns their own guides
drop policy if exists "Users can view own knowledge"        on public.knowledge_guides;
drop policy if exists "Users can insert own knowledge"      on public.knowledge_guides;
drop policy if exists "Users manage own knowledge guides"   on public.knowledge_guides;
create policy "Users manage own knowledge guides" on public.knowledge_guides for all using (auth.uid() = user_id);

-- boolean_searches: a user fully owns their own searches
drop policy if exists "Users can view own searches"        on public.boolean_searches;
drop policy if exists "Users can insert own searches"      on public.boolean_searches;
drop policy if exists "Users manage own boolean searches"  on public.boolean_searches;
create policy "Users manage own boolean searches" on public.boolean_searches for all using (auth.uid() = user_id);

-- user_profiles
drop policy if exists "Users manage own profile" on public.user_profiles;
create policy "Users manage own profile" on public.user_profiles for all using (auth.uid() = id);

-- candidate_notes
drop policy if exists "Users manage own candidate notes" on public.candidate_notes;
create policy "Users manage own candidate notes" on public.candidate_notes for all using (auth.uid() = user_id);

-- candidate_submissions
drop policy if exists "Users manage own submissions" on public.candidate_submissions;
create policy "Users manage own submissions" on public.candidate_submissions for all using (auth.uid() = user_id);

-- market_intelligence
drop policy if exists "Users manage own market intelligence" on public.market_intelligence;
create policy "Users manage own market intelligence" on public.market_intelligence for all using (auth.uid() = user_id);
