-- Migration: Add user_id to jobs, enable RLS, add knowledge + boolean_search storage
-- Run with: supabase db push

-- 1. Add user_id to jobs table (references auth.users)
alter table public.jobs add column if not exists user_id uuid references auth.users(id) on delete cascade;

-- 2. Add knowledge_guides table to persist interview guides
create table if not exists public.knowledge_guides (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  concepts jsonb default '[]'::jsonb,
  interview_questions jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

-- 3. Add boolean_searches table to persist generated queries
create table if not exists public.boolean_searches (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  query text not null,
  created_at timestamptz default now()
);

-- 4. Indexes
create index if not exists idx_jobs_user_id on public.jobs(user_id);
create index if not exists idx_knowledge_guides_job_id on public.knowledge_guides(job_id);
create index if not exists idx_boolean_searches_job_id on public.boolean_searches(job_id);

-- 5. Enable Row Level Security on all tables
alter table public.jobs enable row level security;
alter table public.candidates enable row level security;
alter table public.interview_reports enable row level security;
alter table public.knowledge_guides enable row level security;
alter table public.boolean_searches enable row level security;

-- 6. RLS Policies — users can only access their own data

-- Jobs: user can CRUD their own jobs
create policy "Users can view own jobs" on public.jobs for select using (auth.uid() = user_id);
create policy "Users can insert own jobs" on public.jobs for insert with check (auth.uid() = user_id);
create policy "Users can update own jobs" on public.jobs for update using (auth.uid() = user_id);
create policy "Users can delete own jobs" on public.jobs for delete using (auth.uid() = user_id);

-- Candidates: user can access candidates for their own jobs
create policy "Users can view own candidates" on public.candidates for select using (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);
create policy "Users can insert own candidates" on public.candidates for insert with check (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);
create policy "Users can update own candidates" on public.candidates for update using (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);
create policy "Users can delete own candidates" on public.candidates for delete using (
  exists (select 1 from public.jobs where jobs.id = candidates.job_id and jobs.user_id = auth.uid())
);

-- Interview Reports: user can access reports for their own jobs
create policy "Users can view own reports" on public.interview_reports for select using (
  exists (select 1 from public.jobs where jobs.id = interview_reports.job_id and jobs.user_id = auth.uid())
);
create policy "Users can insert own reports" on public.interview_reports for insert with check (
  exists (select 1 from public.jobs where jobs.id = interview_reports.job_id and jobs.user_id = auth.uid())
);

-- Knowledge Guides: user can access their own guides
create policy "Users can view own knowledge" on public.knowledge_guides for select using (auth.uid() = user_id);
create policy "Users can insert own knowledge" on public.knowledge_guides for insert with check (auth.uid() = user_id);

-- Boolean Searches: user can access their own searches
create policy "Users can view own searches" on public.boolean_searches for select using (auth.uid() = user_id);
create policy "Users can insert own searches" on public.boolean_searches for insert with check (auth.uid() = user_id);
