-- RecruitAI: jobs, candidates, interview_reports
-- Run with: supabase db push (or link to your project and push)

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  role text,
  experience text,
  hard_skills text,
  soft_skills text,
  certifications text,
  created_at timestamptz default now()
);

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.jobs(id) on delete cascade,
  name text not null,
  profile_url text,
  profile_text text not null,
  skills text,
  experience text,
  match_score int default 0,
  match_reasoning text,
  created_at timestamptz default now()
);

create table if not exists public.interview_reports (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  job_id bigint not null references public.jobs(id) on delete cascade,
  notes text not null,
  strengths text,
  weaknesses text,
  recommendation text,
  created_at timestamptz default now()
);

create index if not exists idx_candidates_job_id on public.candidates(job_id);
create index if not exists idx_interview_reports_candidate_id on public.interview_reports(candidate_id);

-- Optional: RLS (enable and add policies when you add auth)
-- alter table public.jobs enable row level security;
-- alter table public.candidates enable row level security;
-- alter table public.interview_reports enable row level security;
